### ISSUE TITLE
这种做法好像没有对Packege Manager导入的模块做处理。

### ISSUE THREAD

**Issue by justinlm** [luckyWjr/ILRuntimeDemo#1]
如果unity工程中有代码使用到了Packege Manager里的模块，好像编译的时候会出现报错。不知道大佬有没有遇到这个问题。

**Comment by luckyWjr** [comment]
Package Manager添加的Package的dll应该是在Library/ScriptAssemblies目录下的，已经添加了。或者试试吧Library/PackageCache中的代码打包进dll

**Comment by justinlm** [comment]
好的。谢谢
